---
version: 1

kind: experiment

framework: xgboost

tags: [train_models]

build:
  image: gitlab.beno.ai:4567/ai/hypgen/sammi:master-cpu-20fdd6ba
  build_steps:
    - pip install -r requirements.txt

run:
  cmd: python predict.py --model xgboost
